"""`loglens init` — scaffold a config file with a fresh PII salt.

(`loglens doctor` — environment diagnostics — is added alongside this module.)
"""

from __future__ import annotations

import secrets
from pathlib import Path
from typing import Annotated, Optional

import typer

_SALT_TOKEN = "__PII_SALT__"

_FULL_TEMPLATE = """\
# LogLens configuration — generated by `loglens init`.
# Docs: https://github.com/adityabhatt/loglens

# SQLite database for findings, errors and baselines
db_path: loglens.db

# Custom PII patterns file (optional)
pii_rules_path: pii_rules.yaml

# Salt for deterministic PII pseudonymisation (generated for you).
# Keep this stable so redaction hashes stay consistent across runs.
# You can also override it with the env var LOGLENS_PII_SALT.
pii_salt: "__PII_SALT__"

# REST API Bearer token — leave empty to disable auth (local dev).
# Prefer the env var LOGLENS_API_TOKEN.
api_token: ""

# Plugin directory — all *.py files here are auto-loaded at startup.
# plugins_dir: plugins/

# Findings persistence
findings_retention_days: 30
findings_min_severity: high   # low | medium | high | critical

# ── LLM provider ──────────────────────────────────────────────────────────
# Local (default): Ollama. For a cloud provider, set `provider` and put the API
# key in an environment variable (e.g. ANTHROPIC_API_KEY) rather than here.
llm:
  provider: ollama            # ollama | claude | openai | groq | mistral | lm_studio
  model: gemma3:4b
  endpoint: http://localhost:11434
  # api_key: ${ANTHROPIC_API_KEY}

# ── Alert channels (optional) ─────────────────────────────────────────────
# Findings at/above each channel's min_severity are pushed on realtime commands.
# alerts:
#   - type: slack
#     url: ${SLACK_WEBHOOK_URL}
#     min_severity: high
#     cooldown: 300            # throttle: at most one repeat per 5 min
#     # escalate_count: 5      # or: only fire after 5 hits within...
#     # escalate_window: 120   # ...120 seconds
"""

_MINIMAL_TEMPLATE = """\
# LogLens configuration (minimal) — generated by `loglens init`.
db_path: loglens.db
pii_salt: "__PII_SALT__"

llm:
  provider: ollama
  model: gemma3:4b
"""


def init(
    output: Annotated[
        Optional[Path],
        typer.Option("--output", "-o", help="Where to write the config (default: ./config.yaml)."),
    ] = None,
    force: Annotated[
        bool, typer.Option("--force", "-f", help="Overwrite an existing config file.")
    ] = False,
    minimal: Annotated[
        bool, typer.Option("--minimal", help="Write a minimal config instead of the full one.")
    ] = False,
) -> None:
    """Generate a config.yaml with a freshly generated PII salt."""
    target = output or Path("config.yaml")

    if target.exists() and not force:
        typer.echo(
            typer.style(
                f"  {target} already exists. Use --force to overwrite.", fg=typer.colors.RED
            ),
            err=True,
        )
        raise typer.Exit(1)

    salt = secrets.token_hex(16)
    template = _MINIMAL_TEMPLATE if minimal else _FULL_TEMPLATE
    content = template.replace(_SALT_TOKEN, salt)

    if target.parent and not target.parent.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    typer.echo(typer.style(f"  Wrote {target}", fg=typer.colors.GREEN))
    typer.echo("  A unique PII salt was generated. Next steps:")
    typer.echo("    - review the file and set your LLM provider / alert channels")
    typer.echo("    - run 'loglens doctor' to check your environment")
