"""`loglens init` — scaffold a config file with a fresh PII salt.

(`loglens doctor` — environment diagnostics — is added alongside this module.)
"""

from __future__ import annotations

import os
import secrets
from pathlib import Path
from typing import Annotated, Optional

import typer

from loglens.config import Config

_SALT_TOKEN = "__PII_SALT__"

_FULL_TEMPLATE = """\
# LogLens configuration — generated by `loglens init`.
# Docs: https://github.com/adityabhatt/loglens

# SQLite database for findings, errors and baselines
db_path: loglens.db

# Custom PII patterns file (optional)
pii_rules_path: pii_rules.yaml

# Salt for deterministic PII pseudonymisation (generated for you).
# Keep this stable so redaction hashes stay consistent across runs.
# You can also override it with the env var LOGLENS_PII_SALT.
pii_salt: "__PII_SALT__"

# REST API Bearer token — leave empty to disable auth (local dev).
# Prefer the env var LOGLENS_API_TOKEN.
api_token: ""

# Plugin directory — all *.py files here are auto-loaded at startup.
# plugins_dir: plugins/

# Findings persistence
findings_retention_days: 30
findings_min_severity: high   # low | medium | high | critical

# ── LLM provider ──────────────────────────────────────────────────────────
# Local (default): Ollama. For a cloud provider, set `provider` and put the API
# key in an environment variable (e.g. ANTHROPIC_API_KEY) rather than here.
llm:
  provider: ollama            # ollama | claude | openai | groq | mistral | lm_studio
  model: gemma3:4b
  endpoint: http://localhost:11434
  # api_key: ${ANTHROPIC_API_KEY}

# ── Alert channels (optional) ─────────────────────────────────────────────
# Findings at/above each channel's min_severity are pushed on realtime commands.
# alerts:
#   - type: slack
#     url: ${SLACK_WEBHOOK_URL}
#     min_severity: high
#     cooldown: 300            # throttle: at most one repeat per 5 min
#     # escalate_count: 5      # or: only fire after 5 hits within...
#     # escalate_window: 120   # ...120 seconds
"""

_MINIMAL_TEMPLATE = """\
# LogLens configuration (minimal) — generated by `loglens init`.
db_path: loglens.db
pii_salt: "__PII_SALT__"

llm:
  provider: ollama
  model: gemma3:4b
"""


def init(
    output: Annotated[
        Optional[Path],
        typer.Option("--output", "-o", help="Where to write the config (default: ./config.yaml)."),
    ] = None,
    force: Annotated[
        bool, typer.Option("--force", "-f", help="Overwrite an existing config file.")
    ] = False,
    minimal: Annotated[
        bool, typer.Option("--minimal", help="Write a minimal config instead of the full one.")
    ] = False,
) -> None:
    """Generate a config.yaml with a freshly generated PII salt."""
    target = output or Path("config.yaml")

    if target.exists() and not force:
        typer.echo(
            typer.style(
                f"  {target} already exists. Use --force to overwrite.", fg=typer.colors.RED
            ),
            err=True,
        )
        raise typer.Exit(1)

    salt = secrets.token_hex(16)
    template = _MINIMAL_TEMPLATE if minimal else _FULL_TEMPLATE
    content = template.replace(_SALT_TOKEN, salt)

    if target.parent and not target.parent.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

    typer.echo(typer.style(f"  Wrote {target}", fg=typer.colors.GREEN))
    typer.echo("  A unique PII salt was generated. Next steps:")
    typer.echo("    - review the file and set your LLM provider / alert channels")
    typer.echo("    - run 'loglens doctor' to check your environment")


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------

_OK = typer.style(" OK ", fg=typer.colors.GREEN)
_WARN = typer.style("WARN", fg=typer.colors.YELLOW)
_FAIL = typer.style("FAIL", fg=typer.colors.RED)


class _Report:
    """Accumulates check results; tracks whether any hard failure occurred."""

    def __init__(self) -> None:
        self.failed = False

    def ok(self, label: str, msg: str) -> None:
        typer.echo(f"  [{_OK}] {label}: {msg}")

    def warn(self, label: str, msg: str) -> None:
        typer.echo(f"  [{_WARN}] {label}: {msg}")

    def fail(self, label: str, msg: str) -> None:
        self.failed = True
        typer.echo(f"  [{_FAIL}] {label}: {msg}")


def doctor(
    config: Annotated[Optional[Path], typer.Option("--config", "-c")] = None,
) -> None:
    """Diagnose configuration and environment; exit non-zero on hard failures."""
    from loglens.llm.factory import _API_KEY_ENV, make_llm_client
    from loglens.notify import build_notifiers
    from loglens.plugins.loader import load_plugins

    rep = _Report()
    typer.echo("\nLogLens environment check\n" + "-" * 40)

    # ── Config ─────────────────────────────────────────────────────────────
    used_path = config or Config.find_config_path()
    if used_path:
        rep.ok("Config", f"using {used_path}")
    else:
        rep.warn("Config", "no config file found — using defaults (run 'loglens init')")
    try:
        cfg = Config.load(config)
    except Exception as e:
        rep.fail("Config", f"failed to load: {e}")
        raise typer.Exit(1) from e

    # ── PII salt ───────────────────────────────────────────────────────────
    if cfg.pii_salt:
        rep.ok("PII salt", "set")
    else:
        rep.warn(
            "PII salt",
            "empty — redaction hashes are not stable; run 'loglens init' or set LOGLENS_PII_SALT",
        )

    # ── Database path ──────────────────────────────────────────────────────
    parent = cfg.db_path.parent if str(cfg.db_path.parent) else Path()
    if not parent.exists():
        rep.fail("Database", f"directory {parent} does not exist")
    elif not os.access(parent, os.W_OK):
        rep.fail("Database", f"directory {parent} is not writable")
    else:
        state = "exists" if cfg.db_path.exists() else "will be created"
        rep.ok("Database", f"{cfg.db_path} ({state})")

    # ── LLM provider ───────────────────────────────────────────────────────
    provider = cfg.llm.provider
    client = make_llm_client(cfg.llm)
    if getattr(client, "is_cloud", False):
        env_vars = _API_KEY_ENV.get(provider, [])
        has_key = bool(cfg.llm.api_key) or any(os.environ.get(v) for v in env_vars)
        if not has_key:
            hint = " or ".join(env_vars) or "llm.api_key"
            rep.fail("LLM", f"cloud provider '{provider}' has no API key (set {hint})")
        else:
            rep.ok("LLM", f"{provider}/{cfg.llm.model} (API key found)")
    else:
        rep.ok("LLM", f"{provider}/{cfg.llm.model} (local)")

    try:
        reachable = client.is_available()
    except Exception:
        reachable = False
    if reachable:
        rep.ok("LLM reachability", f"{provider} is reachable")
    else:
        rep.warn("LLM reachability", f"{provider} not reachable (it may simply be offline)")

    # ── Plugins ────────────────────────────────────────────────────────────
    if cfg.plugins_dir:
        registry = load_plugins(cfg.plugins_dir)
        rep.ok(
            "Plugins",
            f"{cfg.plugins_dir}: {len(registry.rules)} rule(s), "
            f"{len(registry.pii_patterns)} PII, {len(registry.parsers)} parser(s), "
            f"{len(registry.adapters)} adapter(s)",
        )
    else:
        rep.ok("Plugins", "none configured")

    # ── Alert channels ─────────────────────────────────────────────────────
    try:
        notifiers = build_notifiers(cfg.alerts)
    except ValueError as e:
        rep.fail("Alerts", f"invalid configuration: {e}")
    else:
        if not notifiers:
            rep.ok("Alerts", "no channels configured")
        else:
            rep.ok("Alerts", f"{len(notifiers)} channel(s) configured")
            unexpanded = [c.type for c in cfg.alerts if c.url and "${" in c.url]
            if unexpanded:
                rep.warn(
                    "Alerts",
                    f"unset env var(s) in channel url(s): {', '.join(unexpanded)}",
                )

    typer.echo("-" * 40)
    if rep.failed:
        typer.echo(typer.style("  One or more checks FAILED.", fg=typer.colors.RED))
        raise typer.Exit(1)
    typer.echo(typer.style("  All critical checks passed.", fg=typer.colors.GREEN))
